# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circunscripcion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
